User interface for tic-tac-toe.
mahbubul14/tic_toc_toe pull request #3
Opened 2021-05-11 15:09 UTC by mahbubul14

# tic_tac_toe in ruby program (milestone- 2)

## In this milestone we:
- Created a user_interface branch for milestone-2 
- Added content for the user interface
- Added validations to accept string for players username only
- Added validations to pick only 1-9  on board
- Add a loop in the game

2021-05-12 08:26 UTC, mke2111 requested changes
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coders, 👋🏽 
**This is a great project you have going on, well-done lads**. 

### Well-done 💯 
    1. The game requirements are met.
    2. The linter checks are a success.

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [ ] Add a more brief description message to the PR message body.
- [ ] The game should inform the player if the selected move is invalid (without computing what an invalid move is). [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/invalid_move.png)
You need to validate the user input for the board positions(1-9), everything else should be considered invalid.
- [ ] A loop is needed in this game. Inside the loop, you should call actions repeated for each move. The loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable.
```
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner #  (the exact condition in this milestone is not important)
    game_on = false
  end

  if draw # (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

2021-05-12 08:29 UTC, mke2111 commented on bin/main
> +one = gets.chomp
Add restrictions to only allow single digits 1-9.

2021-05-12 08:29 UTC, mke2111 commented on bin/main
> +gets.chomp
Add restrictions to only allow single digits 1-9.

2021-05-12 22:25 UTC, BrianSammit requested changes
CHANGES REQUIRED  :red_circle: 
-------------
Hello @mahbubul14 @prolajumokeoni  you doing an amazing job in this milestone :muscle: :clap: 
However, there is some fix to make to complete this milestone :hammer_and_wrench: see it  below :eyes: :point_down: 
--------------

- [x] When I try to make a second move I got this error. 

![Screenshot from 2021-05-12 17-19-17](https://user-images.githubusercontent.com/64173189/118051453-aad37700-b346-11eb-9a00-5aa4d3feeed0.png)
--------------
 Please make the required change and send it again for another review :+1: 
 HAPPY CODING!!!

![tenor (1)](https://user-images.githubusercontent.com/64173189/118051645-f7b74d80-b346-11eb-8b02-1e63b71d6998.gif)

2021-05-12 22:56 UTC, ElijahTobs requested changes
# Status: Changes Required :recycle: 

## Hi @mahbubul14 and @prolajumokeoni :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there is just a little change to be made before this milestone can be approved.

## HIGHLIGHTS 💯 
- Your PR message is well-detailed ✔️ 
- Descriptive commit messages ✔️ 

## REQUIRED

* [x] Your game should inform players if the selected move is a draw move (without computing draw). [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_tie.png)

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2021-05-13 07:20 UTC, Berabjesus approved these changes
# **Status: PROJECT APPROVED** 
Great job on implementing the changes required @prolajumokeoni and @mahbubul14 Keep it up.  :champagne: :champagne: 
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete. 👍** 

I wish you all the very best in your next tasks:1st_place_medal:
#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help** 
**HAPPY CODING :computer:[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](https://linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-05-13 07:53 UTC, merged